In [1]:
import pandas as pd 
import numpy as np 
import os

In [14]:
filename = os.path.join("geopolitical_events.csv")
df = pd.read_csv(filename)

In [15]:
df.head(20)

,event_id,date,event_type,severity,affected_region,duration_days,risk_increase
0,E000001,2017-05-10 00:00:00,Cyber Attack,8,Europe,195,20.99
1,E000002,2024-06-06 00:00:00,Port Strike,4,South America,158,8.90
2,E000003,2021-07-19 00:00:00,Cyber Attack,6,Asia,198,19.30
3,E000004,2026-04-10 00:00:00,Diplomatic Crisis,9,Africa,55,53.06
4,E000005,2019-12-12 00:00:00,Political Unrest,3,Asia,61,6.56
5,E000006,2025-08-26 00:00:00,Terrorism,7,Europe,27,40.57
6,E000007,2021-06-21 00:00:00,Diplomatic Crisis,2,North America,271,5.85
7,E000008,2019-01-18 00:00:00,War,8,Africa,41,21.83
8,E000009,2023-06-01 00:00:00,Diplomatic Crisis,6,Africa,60,16.44
9,E000010,2015-06-11 00:00:00,Export Restriction,10,South America,276,27.84
10,E000011,2017-10-13 00:00:00,Trade Sanction,8,North America,219,34.78
11,E000012,2016-01-15 00:00:00,War,9,Asia,163,53.53
12,E000013,2020-07-20 00:00:00,Port Strike,8,Asia,69,38.76
13,E000014,2024-10-01 00:00:00,Border Conflict,7,Asia,47,31.45
14,E000015,2023-07-02 00:00:00,Export Restriction,7,North America,68,34.43
15,E000016,2022-08-05 00:00:00,Cyber Attack,3,South America,233,16.19
16,E000017,2017-10-25 00:00:00,Border Conflict,10,Middle East,261,40.91
17,E000018,2019-01-24 00:00:00,Border Conflict,3,Asia,69,9.77
18,E000019,2026-06-23 00:00:00,Cyber Attack,4,North America,228,16.64
19,E000020,2017-11-25 00:00:00,Port Strike,7,South America,193,38.65

In [23]:
#using strftime(Short for string format time) It converts dates into formatted string representations.
df['date'] = pd.to_datetime(df['date'], format='mixed').dt.strftime('%Y-%m-%d')
df.head(20)

,event_id,date,event_type,severity,affected_region,duration_days,risk_increase
0,E000001,2017-05-10,Cyber Attack,8,Europe,195,20.99
1,E000002,2024-06-06,Port Strike,4,South America,158,8.90
2,E000003,2021-07-19,Cyber Attack,6,Asia,198,19.30
3,E000004,2026-04-10,Diplomatic Crisis,9,Africa,55,53.06
4,E000005,2019-12-12,Political Unrest,3,Asia,61,6.56
5,E000006,2025-08-26,Terrorism,7,Europe,27,40.57
6,E000007,2021-06-21,Diplomatic Crisis,2,North America,271,5.85
7,E000008,2019-01-18,War,8,Africa,41,21.83
8,E000009,2023-06-01,Diplomatic Crisis,6,Africa,60,16.44
9,E000010,2015-06-11,Export Restriction,10,South America,276,27.84
10,E000011,2017-10-13,Trade Sanction,8,North America,219,34.78
11,E000012,2016-01-15,War,9,Asia,163,53.53
12,E000013,2020-07-20,Port Strike,8,Asia,69,38.76
13,E000014,2024-10-01,Border Conflict,7,Asia,47,31.45
14,E000015,2023-07-02,Export Restriction,7,North America,68,34.43
15,E000016,2022-08-05,Cyber Attack,3,South America,233,16.19
16,E000017,2017-10-25,Border Conflict,10,Middle East,261,40.91
17,E000018,2019-01-24,Border Conflict,3,Asia,69,9.77
18,E000019,2026-06-23,Cyber Attack,4,North America,228,16.64
19,E000020,2017-11-25,Port Strike,7,South America,193,38.65

In [25]:
#checking for null values
df.isna().sum()

event_id           0
date               0
event_type         0
severity           0
affected_region    0
duration_days      0
risk_increase      0
dtype: int64

In [26]:
#checking for inconsitencies?
print(df['event_type'].unique())
print(df['affected_region'].unique())

['Cyber Attack' 'Port Strike' 'Diplomatic Crisis' 'Political Unrest'
 'Terrorism' 'War' 'Export Restriction' 'Trade Sanction' 'Border Conflict'
 'Maritime Conflict' 'COVID Supply Shock' 'Russia Ukraine War'
 'Red Sea Crisis']
['Europe' 'South America' 'Asia' 'Africa' 'North America' 'Middle East'
 'Global']

In [30]:
#Check for duplicate event IDs
print("Duplicate IDs:", df['event_id'].duplicated().sum())
print("Duplicate Rows:", df.duplicated().sum())

Duplicate IDs: 0
Duplicate Rows: 0

In [28]:
#checking for any outliers
df[['severity', 'duration_days', 'risk_increase']].describe()

           severity  duration_days  risk_increase
count  10003.000000   10003.000000   10003.000000
mean       5.517345     186.382685      21.975127
std        2.867077     104.028748      13.347118
min        1.000000       7.000000       2.010000
25%        3.000000      96.000000      11.060000
50%        6.000000     186.000000      20.230000
75%        8.000000     277.000000      30.990000
max       10.000000    1000.000000      60.000000

In [31]:
df.head()

,event_id,date,event_type,severity,affected_region,duration_days,risk_increase
0,E000001,2017-05-10,Cyber Attack,8,Europe,195,20.99
1,E000002,2024-06-06,Port Strike,4,South America,158,8.90
2,E000003,2021-07-19,Cyber Attack,6,Asia,198,19.30
3,E000004,2026-04-10,Diplomatic Crisis,9,Africa,55,53.06
4,E000005,2019-12-12,Political Unrest,3,Asia,61,6.56

In [32]:
df.to_csv('cleaned_geopolitical_events.csv', index=False)

## Checking Weekly_timeline.csv

In [33]:
filenamee = os.path.join("weekly_timeline.csv")
dt = pd.read_csv(filenamee)

In [35]:
dt.head(20)

          date
0   2015-01-04
1   2015-01-11
2   2015-01-18
3   2015-01-25
4   2015-02-01
5   2015-02-08
6   2015-02-15
7   2015-02-22
8   2015-03-01
9   2015-03-08
10  2015-03-15
11  2015-03-22
12  2015-03-29
13  2015-04-05
14  2015-04-12
15  2015-04-19
16  2015-04-26
17  2015-05-03
18  2015-05-10
19  2015-05-17

In [45]:
dt.isna().sum()

date    0
dtype: int64

In [44]:
#checking for inconsitencies?
print(dt['date'].unique())

['2015-01-04' '2015-01-11' '2015-01-18' '2015-01-25' '2015-02-01'
 '2015-02-08' '2015-02-15' '2015-02-22' '2015-03-01' '2015-03-08'
 '2015-03-15' '2015-03-22' '2015-03-29' '2015-04-05' '2015-04-12'
 '2015-04-19' '2015-04-26' '2015-05-03' '2015-05-10' '2015-05-17'
 '2015-05-24' '2015-05-31' '2015-06-07' '2015-06-14' '2015-06-21'
 '2015-06-28' '2015-07-05' '2015-07-12' '2015-07-19' '2015-07-26'
 '2015-08-02' '2015-08-09' '2015-08-16' '2015-08-23' '2015-08-30'
 '2015-09-06' '2015-09-13' '2015-09-20' '2015-09-27' '2015-10-04'
 '2015-10-11' '2015-10-18' '2015-10-25' '2015-11-01' '2015-11-08'
 '2015-11-15' '2015-11-22' '2015-11-29' '2015-12-06' '2015-12-13'
 '2015-12-20' '2015-12-27' '2016-01-03' '2016-01-10' '2016-01-17'
 '2016-01-24' '2016-01-31' '2016-02-07' '2016-02-14' '2016-02-21'
 '2016-02-28' '2016-03-06' '2016-03-13' '2016-03-20' '2016-03-27'
 '2016-04-03' '2016-04-10' '2016-04-17' '2016-04-24' '2016-05-01'
 '2016-05-08' '2016-05-15' '2016-05-22' '2016-05-29' '2016-06-05'
 '2016-06-12' '2016-06-19' '2016-06-26' '2016-07-03' '2016-07-10'
 '2016-07-17' '2016-07-24' '2016-07-31' '2016-08-07' '2016-08-14'
 '2016-08-21' '2016-08-28' '2016-09-04' '2016-09-11' '2016-09-18'
 '2016-09-25' '2016-10-02' '2016-10-09' '2016-10-16' '2016-10-23'
 '2016-10-30' '2016-11-06' '2016-11-13' '2016-11-20' '2016-11-27'
 '2016-12-04' '2016-12-11' '2016-12-18' '2016-12-25' '2017-01-01'
 '2017-01-08' '2017-01-15' '2017-01-22' '2017-01-29' '2017-02-05'
 '2017-02-12' '2017-02-19' '2017-02-26' '2017-03-05' '2017-03-12'
 '2017-03-19' '2017-03-26' '2017-04-02' '2017-04-09' '2017-04-16'
 '2017-04-23' '2017-04-30' '2017-05-07' '2017-05-14' '2017-05-21'
 '2017-05-28' '2017-06-04' '2017-06-11' '2017-06-18' '2017-06-25'
 '2017-07-02' '2017-07-09' '2017-07-16' '2017-07-23' '2017-07-30'
 '2017-08-06' '2017-08-13' '2017-08-20' '2017-08-27' '2017-09-03'
 '2017-09-10' '2017-09-17' '2017-09-24' '2017-10-01' '2017-10-08'
 '2017-10-15' '2017-10-22' '2017-10-29' '2017-11-05' '2017-11-12'
 '2017-11-19' '2017-11-26' '2017-12-03' '2017-12-10' '2017-12-17'
 '2017-12-24' '2017-12-31' '2018-01-07' '2018-01-14' '2018-01-21'
 '2018-01-28' '2018-02-04' '2018-02-11' '2018-02-18' '2018-02-25'
 '2018-03-04' '2018-03-11' '2018-03-18' '2018-03-25' '2018-04-01'
 '2018-04-08' '2018-04-15' '2018-04-22' '2018-04-29' '2018-05-06'
 '2018-05-13' '2018-05-20' '2018-05-27' '2018-06-03' '2018-06-10'
 '2018-06-17' '2018-06-24' '2018-07-01' '2018-07-08' '2018-07-15'
 '2018-07-22' '2018-07-29' '2018-08-05' '2018-08-12' '2018-08-19'
 '2018-08-26' '2018-09-02' '2018-09-09' '2018-09-16' '2018-09-23'
 '2018-09-30' '2018-10-07' '2018-10-14' '2018-10-21' '2018-10-28'
 '2018-11-04' '2018-11-11' '2018-11-18' '2018-11-25' '2018-12-02'
 '2018-12-09' '2018-12-16' '2018-12-23' '2018-12-30' '2019-01-06'
 '2019-01-13' '2019-01-20' '2019-01-27' '2019-02-03' '2019-02-10'
 '2019-02-17' '2019-02-24' '2019-03-03' '2019-03-10' '2019-03-17'
 '2019-03-24' '2019-03-31' '2019-04-07' '2019-04-14' '2019-04-21'
 '2019-04-28' '2019-05-05' '2019-05-12' '2019-05-19' '2019-05-26'
 '2019-06-02' '2019-06-09' '2019-06-16' '2019-06-23' '2019-06-30'
 '2019-07-07' '2019-07-14' '2019-07-21' '2019-07-28' '2019-08-04'
 '2019-08-11' '2019-08-18' '2019-08-25' '2019-09-01' '2019-09-08'
 '2019-09-15' '2019-09-22' '2019-09-29' '2019-10-06' '2019-10-13'
 '2019-10-20' '2019-10-27' '2019-11-03' '2019-11-10' '2019-11-17'
 '2019-11-24' '2019-12-01' '2019-12-08' '2019-12-15' '2019-12-22'
 '2019-12-29' '2020-01-05' '2020-01-12' '2020-01-19' '2020-01-26'
 '2020-02-02' '2020-02-09' '2020-02-16' '2020-02-23' '2020-03-01'
 '2020-03-08' '2020-03-15' '2020-03-22' '2020-03-29' '2020-04-05'
 '2020-04-12' '2020-04-19' '2020-04-26' '2020-05-03' '2020-05-10'
 '2020-05-17' '2020-05-24' '2020-05-31' '2020-06-07' '2020-06-14'
 '2020-06-21' '2020-06-28' '2020-07-05' '2020-07-12' '2020-07-19'
 '2020-07-26' '2020-08-02' '2020-08-09' '2020-08-16' '2020-08-23'
 '2020-08-30' '2020-09-06' '2020-09-13' '2020-09-20' '2020-09-27'
 '2020-10-04' '2020-10-11' '2020-10-18' '2020-10-25' '2020-11-01'
 '2020-11-08' '2020-11-15' '2020-11-22' '2020-11-29' '2020-12-06'
 '2020-12-13' '2020-12-20' '2020-12-27' '2021-01-03' '2021-01-10'
 '2021-01-17' '2021-01-24' '2021-01-31' '2021-02-07' '2021-02-14'
 '2021-02-21' '2021-02-28' '2021-03-07' '2021-03-14' '2021-03-21'
 '2021-03-28' '2021-04-04' '2021-04-11' '2021-04-18' '2021-04-25'
 '2021-05-02' '2021-05-09' '2021-05-16' '2021-05-23' '2021-05-30'
 '2021-06-06' '2021-06-13' '2021-06-20' '2021-06-27' '2021-07-04'
 '2021-07-11' '2021-07-18' '2021-07-25' '2021-08-01' '2021-08-08'
 '2021-08-15' '2021-08-22' '2021-08-29' '2021-09-05' '2021-09-12'
 '2021-09-19' '2021-09-26' '2021-10-03' '2021-10-10' '2021-10-17'
 '2021-10-24' '2021-10-31' '2021-11-07' '2021-11-14' '2021-11-21'
 '2021-11-28' '2021-12-05' '2021-12-12' '2021-12-19' '2021-12-26'
 '2022-01-02' '2022-01-09' '2022-01-16' '2022-01-23' '2022-01-30'
 '2022-02-06' '2022-02-13' '2022-02-20' '2022-02-27' '2022-03-06'
 '2022-03-13' '2022-03-20' '2022-03-27' '2022-04-03' '2022-04-10'
 '2022-04-17' '2022-04-24' '2022-05-01' '2022-05-08' '2022-05-15'
 '2022-05-22' '2022-05-29' '2022-06-05' '2022-06-12' '2022-06-19'
 '2022-06-26' '2022-07-03' '2022-07-10' '2022-07-17' '2022-07-24'
 '2022-07-31' '2022-08-07' '2022-08-14' '2022-08-21' '2022-08-28'
 '2022-09-04' '2022-09-11' '2022-09-18' '2022-09-25' '2022-10-02'
 '2022-10-09' '2022-10-16' '2022-10-23' '2022-10-30' '2022-11-06'
 '2022-11-13' '2022-11-20' '2022-11-27' '2022-12-04' '2022-12-11'
 '2022-12-18' '2022-12-25' '2023-01-01' '2023-01-08' '2023-01-15'
 '2023-01-22' '2023-01-29' '2023-02-05' '2023-02-12' '2023-02-19'
 '2023-02-26' '2023-03-05' '2023-03-12' '2023-03-19' '2023-03-26'
 '2023-04-02' '2023-04-09' '2023-04-16' '2023-04-23' '2023-04-30'
 '2023-05-07' '2023-05-14' '2023-05-21' '2023-05-28' '2023-06-04'
 '2023-06-11' '2023-06-18' '2023-06-25' '2023-07-02' '2023-07-09'
 '2023-07-16' '2023-07-23' '2023-07-30' '2023-08-06' '2023-08-13'
 '2023-08-20' '2023-08-27' '2023-09-03' '2023-09-10' '2023-09-17'
 '2023-09-24' '2023-10-01' '2023-10-08' '2023-10-15' '2023-10-22'
 '2023-10-29' '2023-11-05' '2023-11-12' '2023-11-19' '2023-11-26'
 '2023-12-03' '2023-12-10' '2023-12-17' '2023-12-24' '2023-12-31'
 '2024-01-07' '2024-01-14' '2024-01-21' '2024-01-28' '2024-02-04'
 '2024-02-11' '2024-02-18' '2024-02-25' '2024-03-03' '2024-03-10'
 '2024-03-17' '2024-03-24' '2024-03-31' '2024-04-07' '2024-04-14'
 '2024-04-21' '2024-04-28' '2024-05-05' '2024-05-12' '2024-05-19'
 '2024-05-26' '2024-06-02' '2024-06-09' '2024-06-16' '2024-06-23'
 '2024-06-30' '2024-07-07' '2024-07-14' '2024-07-21' '2024-07-28'
 '2024-08-04' '2024-08-11' '2024-08-18' '2024-08-25' '2024-09-01'
 '2024-09-08' '2024-09-15' '2024-09-22' '2024-09-29' '2024-10-06'
 '2024-10-13' '2024-10-20' '2024-10-27' '2024-11-03' '2024-11-10'
 '2024-11-17' '2024-11-24' '2024-12-01' '2024-12-08' '2024-12-15'
 '2024-12-22' '2024-12-29' '2025-01-05' '2025-01-12' '2025-01-19'
 '2025-01-26' '2025-02-02' '2025-02-09' '2025-02-16' '2025-02-23'
 '2025-03-02' '2025-03-09' '2025-03-16' '2025-03-23' '2025-03-30'
 '2025-04-06' '2025-04-13' '2025-04-20' '2025-04-27' '2025-05-04'
 '2025-05-11' '2025-05-18' '2025-05-25' '2025-06-01' '2025-06-08'
 '2025-06-15' '2025-06-22' '2025-06-29' '2025-07-06' '2025-07-13'
 '2025-07-20' '2025-07-27' '2025-08-03' '2025-08-10' '2025-08-17'
 '2025-08-24' '2025-08-31' '2025-09-07' '2025-09-14' '2025-09-21'
 '2025-09-28' '2025-10-05' '2025-10-12' '2025-10-19' '2025-10-26'
 '2025-11-02' '2025-11-09' '2025-11-16' '2025-11-23' '2025-11-30'
 '2025-12-07' '2025-12-14' '2025-12-21' '2025-12-28' '2026-01-04'
 '2026-01-11' '2026-01-18' '2026-01-25' '2026-02-01' '2026-02-08'
 '2026-02-15' '2026-02-22' '2026-03-01' '2026-03-08' '2026-03-15'
 '2026-03-22' '2026-03-29' '2026-04-05' '2026-04-12' '2026-04-19'
 '2026-04-26' '2026-05-03' '2026-05-10' '2026-05-17' '2026-05-24'
 '2026-05-31' '2026-06-07' '2026-06-14' '2026-06-21' '2026-06-28'
 '2026-07-05' '2026-07-12' '2026-07-19' '2026-07-26' '2026-08-02'
 '2026-08-09' '2026-08-16' '2026-08-23' '2026-08-30' '2026-09-06'
 '2026-09-13' '2026-09-20' '2026-09-27' '2026-10-04' '2026-10-11'
 '2026-10-18' '2026-10-25' '2026-11-01' '2026-11-08' '2026-11-15'
 '2026-11-22' '2026-11-29' '2026-12-06' '2026-12-13' '2026-12-20'
 '2026-12-27']

In [43]:
print("Duplicate Dates:", dt['date'].duplicated().sum())

Duplicate Dates: 0

In [48]:
dt[['date']].describe()

              date
count          626
unique         626
top     2015-01-04
freq             1

In [51]:
dt.to_csv('cleaned_weekly_timeline.csv', index=False)